=== JauneArc/Past-Projects/Databases/SQL/Modelling and Validating XML Documents/task3-1.dtd
<!ELEMENT employee (enum,fname,lname,progskills)>
<!ELEMENT progskills (planguage*)>
<!ELEMENT enum (#PCDATA)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT planguage (#PCDATA)>

=== JauneArc/Past-Projects/Databases/SQL/Modelling and Validating XML Documents/documents8/task3-1.xml
<?xml version="1.0"?>

<!DOCTYPE Task3-1 SYSTEM "Task3-1.dtd">
<employee>
  
<enum>007</enum>
  
<fname>James</fname>
  
<lname>Bond</lname>
  
<progskills>
    
<planguage>C++</planguage>
    
<planguage>Java</planguage>
    
<planguage>SQL</planguage>
  
</progskills>

</employee>
