=== JauneArc/Past-Projects/Databases/SQL/Modelling and Validating XML Documents/task4-4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="items" type="ItemsType"/>
<xsd:complexType name="ItemsType">
    <xsd:sequence>
      <xsd:element name="item"  maxOccurs="unbounded" type="ItemType"/>
    </xsd:sequence>

</xsd:complexType>
  <xsd:complexType name="ItemType">
    <xsd:sequence>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="price" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

</xsd:schema>

=== JauneArc/Past-Projects/Databases/SQL/Modelling and Validating XML Documents/documents8/task4-4.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="task4-4.xsd">
  
	<item>
    
		<name>yellow bolt</name>
    
		<price>24</price>
  
	</item>
  
	<item>
    
		<name>green bolt</name>
    
		<price>25</price>
  
	</item>
  
	<item>
    
		<name>white nut</name>
    
		<price>five</price>
  
	</item>
  
	<item>
    
		<name>green nut</name>
    
	<price>eleven</price>
  
	</item>

</items>
